kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: webhook-route
spec:
  parentRefs:
  - name: internal-https-gateway
  rules:
  # Rule 1: Route Dialogflow Client requests (Frontend API)
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: client-backend-svc
      port: 80
  # Rule 2: Default to Webhook Service (Existing logic)
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: webhook-backend-svc
      port: 8080